### ISSUE TITLE
No Sound

### ISSUE THREAD

**Issue by SiriusAshling** [mod-kitchen/hs-next#22]
For me the game does not play any sound, including music and sound effects.
OS: Windows 10
Build: hs-next_test_build_02-WINDOWS
Maybe noteworthy: The game doesn't appear in the Volume Mixer.

**Comment by Glitchfinder** [comment]
Just to confirm, the game currently is set to play sound and music in the settings menu? If so, would you be able to check the log window for audio related messages? The expected messages are at the start and look like this:
```
[2023-12-16T11:36:17][INFO] Enumerating audio devices...
[2023-12-16T11:36:18][INFO] Opening audio device...
```

**Comment by VibrantLGBT** [comment]
I'd also like to confirm that you have an OpenAL32.dll somewhere in the project folder. Should be located in [game root]/System/, usually. but should work in [game root] as well. pretty sure I bundled one, check that your security didn't remove it, because that file missing would cause 'no sound'. might also check that it's Unblocked in file properties.

**Comment by SiriusAshling** [comment]
On startup I get these messages:
```
[2023-12-16T21:07:40][INFO] Enumerating audio devices...
[2023-12-16T21:07:40][INFO] Opening audio device...
```
Beyond that I don't see any audio related messages

I have `[game root]/System/OpenAL32.dll`.
Moving it into `[game root]/OpenAL32.dll` changes nothing.
Removing it causes the game to crash on startup.

**Comment by VibrantLGBT** [comment]
[Edit] snipped suggestion. it's not going to help. hmm.
Edit 2: unsnipping, since apparently it did help.
Requested user to install OpenAL 1.1 from here: https://openal.org/downloads/

Currently exploring an alternative solution.
