### ISSUE TITLE
Interactive HUD doesn't show keys while door is on screen

### ISSUE THREAD

**Issue by SiriusAshling** [mod-kitchen/hs-next#59]
If a door is visible, but far away, the interactive HUD doesn't show the repsective keys until you walk closer

**Comment by Glitchfinder** [comment]
Currently the interactive HUD only shows relevant information within a few tiles. Full-screen relevance is much more complex.

**Comment by Glitchfinder** [comment]
After discussion with @viberrant, this issue is being closed. We have no plans to extend the HUD's relevance popup to the full scope of the screen. The current setup is designed to show relevance to all objects within a few tiles of the player, which includes offscreen objects and can help fuel exploration as a result. Changing that to fullscreen means changing the underlying logic, and will mean that we either cannot show relevance for hidden objects or wind up providing a mechanical advantage to players with larger screens.
